language: python
python:
  - "3.6"
script: pytest
services:
  - docker
deploy:
  provider: heroku
  api_key: 6d119b62-8c80-46c1-b021-b82dc30ca88e
  app: tps-dbservice
  run:
    - "python rabbit_client.py"
